### ISSUE TITLE
Fix table artifact rendering

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/MMM-Tabulator#2]
There is a difference in the rendering of the table, depending on if you are looking at the local host Mirror or on the server. The artifact renders like this:

On the `local host` (RPi3):

![mmm-tabulator_local_425x270](https://user-images.githubusercontent.com/194392/36482355-b613aea2-171b-11e8-9d6c-e4d659a848a4.png)

On the `remote host` using **Firefox**:

![mmm-tabulator_server_ff](https://user-images.githubusercontent.com/194392/36482398-d948907c-171b-11e8-9f4a-219c6fcb1e85.png)

I'd like to get rid of this difference.

**Comment by raywo** [comment]
Usually this is a problem with the css. Have a look at the css provided by the tabulator framework.

**Comment by E3V3A** [comment]
@raywo  Yeah, probably a CSS problem, but I can't find it... It was a PITA just to get the colors right. ;) 
BTW. That pi screen is in portrait mode & orientation, so I'm not sure how this affects MMM's.

**Comment by E3V3A** [comment]
I don't know how to go about fixing this, and I don't have time to look into it. 
If someone has any ideas or fixes, please re-open, send a PR or let me know.
