### ISSUE TITLE
Make module accept dirty JSON data

### ISSUE THREAD

**Issue by E3V3A** [E3V3A/MMM-Tabulator#5]
Currently the module only renders *perfectly* formatted JSON data. However, APIs are often very relaxed when providing JSON data. 

```bash
# cat dirty.json

  { id: '1',
    somenumber: 112233,
    somestring: 'ABCD',
    somenull: null 
  },
  { id: '2',
    somenumber: 445566,
    somestring: 'EFGH',
    somenull: null
  }
```

```json
# cat clean.json

  { "id": "1",
    "somenumber": 112233,
    "somestring": "ABCD",
    "somenull": null
  },
  { "id": "2",
    "somenumber": 445566,
    "somestring": "EFGH",
    "somenull": null
  }


```

 * Also, how [should we](https://stackoverflow.com/questions/21120999/representing-null-in-json) handle `null`? 

I already tried using ` JSON.stringify(data);` before sending it down the socket, but that didn't work as I expected, and no error reason was given...AFAICR. 

Here is some [more JSON documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify).

**Comment by raywo** [comment]
It is indeed true that not all APIs provide nicely formatted JSON. Usually you receive the data in some form or another via a callback function. In this callback you can try to parse the received data via [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse). The result should be nicely formatted json which you can send through your program.

**Comment by E3V3A** [comment]
Hi @raywo !
Is it better to parse it before sending to the socket (in node_helper.js) or after receiving it at the module (MMM-Tabulate.js)? (And what are the arguments if there is a preference?)

Using the original (dirty) demo.json,  I just tried to do: 
```javascript

            let cleanData = JSON.parse(data); // Fix dirty JSON
            console.log("\nRead file data: " + cleanData);
            this.sendSocketNotification("NEW_DATA", cleanData);
```

but I get hit by: 

```
SyntaxError: Unexpected token i in JSON at position 6
    at fs.readFile (/home/pi/MagicMirror/modules/MMM-Tabulator/node_helper.js:43:25)
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

**Comment by raywo** [comment]
> Is it better to parse it before sending to the socket (in node_helper.js) or after receiving it at the module (MMM-Tabulate.js)?

You should ask yourself “Who is responsible for reading the data an providing a useful object to work with?“
I would say the helper is responsible since the responsibility of `MMM-Tabulate.js` is to display data not to manipulate it.

As with your error: Try `console.log(cleanData);`

**Comment by E3V3A** [comment]
> I would say the helper is responsible since the responsibility of MMM-Tabulate.js is to display data not to manipulate it.

I agree, so that's where I tried to change it.

> As with your error: Try console.log(cleanData);

I don't think that would make a difference, because the error is pointing to the parse line before... There must be something else going on...

**Comment by E3V3A** [comment]
I found this [dirty-json](https://github.com/RyanMarcus/dirty-json) parser. Perhaps I'll give this a try...

**Comment by E3V3A** [comment]
That parser *look* good, but installs another 6 packages, and then doesn't work. I think I've solved it the REGEX way, since my JSON data is simple and trust worthy...  :rofl:

**Comment by E3V3A** [comment]
Fixed!

Sanitized Demo data with:

```js
function jZen(data) {
    let re1 = /([A-Za-z0-9_\-]+):/gm;       // Find all ASCII words $1 before an ":"
    let str = "";
    str = data.replace(/\s/gm, '');         // Remove all white-space 
    str = str.replace(/\'/gm, '\"');        // Replace all ' with "     
    str = str.replace(re1, '\"$1\":');      // Replace $1: with "$1":
    //console.log("Dirty JSON is:\n" + data.toString() );
    //console.log("Clean JSON is:\n" + str);
    return str;
}
```
